# Generated by Django 5.0.3 on 2024-04-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('CIDADE', models.CharField(default='Frederico Westphalen', max_length=30, primary_key=True, serialize=False)),
                ('BAIRRO', models.CharField(max_length=30)),
                ('RUA', models.CharField(max_length=30)),
                ('NUMERO', models.CharField(max_length=5, null=True)),
                ('COMPLEMENTO', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'ENDERECO',
            },
        ),
        migrations.CreateModel(
            name='RegistroDeInsidentes',
            fields=[
                ('COD_REGISTRO', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('TIPO_INSIDENTE', models.CharField(max_length=30)),
                ('DESCRICAO_INSIDENTE', models.CharField(max_length=500, null=True)),
            ],
            options={
                'db_table': 'REGISTRO_INSIDENTES',
            },
        ),
    ]
