# Generated by Django 5.0.3 on 2024-05-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Coleta_de_Lixo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkEndereco',
            fields=[
                ('COD_LINK', models.AutoField(primary_key=True, serialize=False)),
                ('ENDERECO_URL', models.URLField()),
            ],
        ),
    ]
