# Generated by Django 5.0.3 on 2024-04-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Coleta_de_Lixo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='COD_CIDADE',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='CIDADE',
            field=models.CharField(default='Frederico Westphalen', max_length=30),
        ),
    ]
