# Generated by Django 5.0.3 on 2024-05-18 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_Coleta_de_Lixo', '0002_linkendereco'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='linkendereco',
            table='LINK_ENDERECO',
        ),
    ]
