# Generated by Django 5.0.3 on 2024-05-18 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Coleta_de_Lixo', '0003_alter_linkendereco_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkendereco',
            name='NOME_LINK',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
