# Generated by Django 5.0.3 on 2024-05-23 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Coleta_de_Lixo', '0005_linkendereco_latitude_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodeinsidentes',
            name='ENDERECO',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_Coleta_de_Lixo.endereco'),
            preserve_default=False,
        ),
    ]
